---
- name: Converge
  hosts: instance
  become: true
  tasks:
    - name: "Include alloy role"
      ansible.builtin.include_role:
        name: calopsys.observability.alloy
      vars:
        calopsys_alloy_config_template: minimal.j2
        calopsys_alloy_prometheus_endpoint_url: "http://localhost:9009/api/v1/push"
        calopsys_alloy_loki_endpoint_url: "http://localhost:3100/loki/api/v1/push"
